### PR TITLE
Fix issue 56

### PR DESCRIPTION
**Pull request by thenewguy**
Fixes issue #56

### CODE REVIEW

**Comment by thenewguy** [comment]
I will also fix issue #57 in this PR for ease of merging since I am working on them together for the same test project

**Comment by thenewguy** [comment]
Commit 15a5fedc38e7bc764c6c03b75c7fcad25aab86c0 resolved conversation https://github.com/tox-dev/tox-docker/pull/62#discussion_r433905767

**Comment by dcrosta** [comment]
A few other things:

1. https://docs.docker.com/network/links/ says that links are deprecated, and we should use user-defined networks instead. It probably makes sense for containers to join a per-test-env network for the test run. It sounds like this should let the containers communicate amongst themselves? I've never needed this so I have no hands-on experience.

2. I'm not certain that we're picking the best values for the linked names, since we aren't controlling the name of the containers we run (we get the auto-generated things). eg:

```
dcrosta@dropwing.local:~ $ docker ps
CONTAINER ID        IMAGE                 COMMAND                  CREATED             STATUS              PORTS                                              NAMES
90ab5be069d2        elasticsearch:7.7.0   "/tini -- /usr/local…"   2 seconds ago       Up 1 second         0.0.0.0:32795->9200/tcp, 0.0.0.0:32794->9300/tcp   romantic_williams
e8c9338ff3c1        postgres:alpine       "docker-entrypoint.s…"   2 seconds ago       Up 1 second         0.0.0.0:32793->5432/tcp                            magical_mendeleev
e8f330494e5a        memcached:alpine      "docker-entrypoint.s…"   3 seconds ago       Up 2 seconds        0.0.0.0:32792->11211/tcp                           amazing_mayer
dcrosta@dropwing.local:~ $ docker inspect 90ab5be069d2 | grep -A 4 Links
            "Links": [
                "/magical_mendeleev:/romantic_williams/e8c9338ff3c1c80df5fc1c38d88a9817414a08594a82819c8e1784a3687f792f",
                "/amazing_mayer:/romantic_williams/a-user-specified-alias"
            ],
```

I'm not sure how to read that, but it looks like the hostname of postgres within the elasticsearch container, since we didn't define an alias, is `e8c9338ff3c1c80df5fc1c38d88a9817414a08594a82819c8e1784a3687f792f`. We should either pick a predictable default (maybe the image basename) or require users to specify an alias, I think.

**Comment by thenewguy** [comment]
> A few other things:
> 
> 1. https://docs.docker.com/network/links/ says that links are deprecated, and we should use user-defined networks instead. It probably makes sense for containers to join a per-test-env network for the test run. It sounds like this should let the containers communicate amongst themselves? I've never needed this so I have no hands-on experience.
> 2. I'm not certain that we're picking the best values for the linked names, since we aren't controlling the name of the containers we run (we get the auto-generated things). eg:
> 
> ```
> dcrosta@dropwing.local:~ $ docker ps
> CONTAINER ID        IMAGE                 COMMAND                  CREATED             STATUS              PORTS                                              NAMES
> 90ab5be069d2        elasticsearch:7.7.0   "/tini -- /usr/local…"   2 seconds ago       Up 1 second         0.0.0.0:32795->9200/tcp, 0.0.0.0:32794->9300/tcp   romantic_williams
> e8c9338ff3c1        postgres:alpine       "docker-entrypoint.s…"   2 seconds ago       Up 1 second         0.0.0.0:32793->5432/tcp                            magical_mendeleev
> e8f330494e5a        memcached:alpine      "docker-entrypoint.s…"   3 seconds ago       Up 2 seconds        0.0.0.0:32792->11211/tcp                           amazing_mayer
> dcrosta@dropwing.local:~ $ docker inspect 90ab5be069d2 | grep -A 4 Links
>             "Links": [
>                 "/magical_mendeleev:/romantic_williams/e8c9338ff3c1c80df5fc1c38d88a9817414a08594a82819c8e1784a3687f792f",
>                 "/amazing_mayer:/romantic_williams/a-user-specified-alias"
>             ],
> ```
> 
> I'm not sure how to read that, but it looks like the hostname of postgres within the elasticsearch container, since we didn't define an alias, is `e8c9338ff3c1c80df5fc1c38d88a9817414a08594a82819c8e1784a3687f792f`. We should either pick a predictable default (maybe the image basename) or require users to specify an alias, I think.

I chose links because it works and the integration was small.  I think it added around 30 lines of code.  And it covers most (maybe all?) use cases needed for testing.

I think it would make sense to support networks but that is more complicated than it sounds.  As long as links is available networks is probably overkill here.  Plus links is immediately useful and would not conflict with networks once implemented.

Aside: aws documentation still uses links - https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/create_deploy_docker_v2config.html
I don't imagine it links will disappear soon.  The docker docs only say it is a legacy feature and "may" eventually be removed.

**Comment by thenewguy** [comment]
@dcrosta I can require an alias if you like.  I can't think of a good use for not using an alias - but I allowed it because docker allows it so I figured there was a valid use case I haven't worked with yet

**Comment by thenewguy** [comment]
replaced by https://github.com/tox-dev/tox-docker/pull/58

**Comment by thenewguy** [comment]
replaced by https://github.com/tox-dev/tox-docker/pull/64

**Pull request closed without merging**
